title: Fortetude
description: A self-assessment and practice tool for traceurs
theme: just-the-docs

url: https://fortetude.github.io
repository: fortetude/fortetude # for github-metadata

aux_links_new_tab: true
aux_links:
  Online Demo: https://fortetude.github.io/app
  Docs Repo: https://github.com/fortetude/fortetude.github.io

nav_external_links: 
- title: Report issues
  url: https://github.com/fortetude/fortetude/issues

# Google Analytics
ga_tracking: G-44CSVHJ1JC

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: default

logo: "/assets/images/fortetude.svg"

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"
gh_edit_link: false # show or hide edit this page link

heading_anchors: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


footer_content: 'Made with ❤️ by <a href="https://github.com/kawing-ho">kawing-ho</a>, for traceurs by traceurs.'